version: "3.7"

services:

    traefik:
      image: traefik:v2.8.1
      ports:
          - 80:80
          - 443:443
      volumes:
          - ./service/traefik/config/traefik.yaml:/etc/traefik/traefik.yaml
          - ./service/traefik/rules:/rules
          - ./service/traefik/log/:/log
          - ./service/traefik/letsencrypt:/letsencrypt
          - ./service/traefik/data:/data
          - /var/run/docker.sock:/var/run/docker.sock:ro
            
    ok:
      image: peterevans/ok-server:latest
      labels:
        traefik.enable: "True"
        traefik.http.routers.ok.entrypoints: websecure
        traefik.http.routers.ok.middlewares: chain-no-auth@file
        traefik.http.routers.ok.rule: Host(`ok.$TOP_LEVEL_DOMAIN`)
        traefik.http.routers.ok.service: ok
        traefik.http.routers.ok.tls: "True"
        traefik.http.routers.ok.tls.certresolver: letsencryptresolver
        traefik.http.services.ok.loadbalancer.server.port: '8080'
