log:
    level: DEBUG
    filePath: /log/traefik.log

accessLog:
    filePath: /log/access.log
    format: json
    fields:
        defaultMode: "keep"
        headers:
          defaultMode: "keep"

api:
    dashboard: false

providers:
    file:
        filename: /rules/rules.yml
        watch: true
    docker:
        endpoint: "unix:///var/run/docker.sock"
        watch: true
        swarmMode: false
        exposedbydefault: false

entrypoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: websecure
                    scheme: https
                    permanent: true
    websecure:
        address: ":443"

certificatesresolvers:
    letsencryptresolver:
        acme:
            httpchallenge:
                entrypoint: web
            email: admin@androiddev.social
            storage: /letsencrypt/acme.json
